#' Function to simulate metapopulation dynamics with infection(poisson number version)
#' @param n_patches Number of patches
#' @param n_years Number of years to simulate
#' @param K Carrying capacity per patch
#' @param r Growth rate
#' @param c0 Migration probability (host movement)
#' @param nu Scaling constant linking dead hosts to total propagules 
#' @param rho Carrying capacity of propagules per migrating live host 
#' @param alpha Transmission efficiency per propagule 
#' @param D Disease-induced mortality 
#' @param R0 basic reproduction number
#' @param initial_inf_ratio Ratio of initially infected patches
#' @param initial_pop_ratio Initial population as ratio of carrying capacity
#' @return A list containing arrays:
#' N (n_patches x n_years x 4), I (n_patches x n_years x 4), total_inf (n_years)
simulate_metapopulation <- function(
    n_patches = 100,
    n_years = 500,
    K = 1e6,
    r = 0.5,
    c0 = 0.2,
    nu = 5,       
    rho = 3,      
    alpha = 5e-6,   
    D = 1,
    R0 = 2,
    initial_inf_ratio = 0.1,
    initial_pop_ratio = 1,
    early_stop = TRUE               
) {
  if (!require("burnout", quietly = TRUE)) stop("please install burnout package")
  
  # Stages: 1 = beginning of year
  #         2 = after growth
  #         3 = after colonization (host movement) + infection introduction + fizzle
  #         4 = after major epidemic (end of year)
  
  N <- array(0, dim = c(n_patches, n_years, 4))
  I <- array(0, dim = c(n_patches, n_years, 4))
  
  total_inf <- rep(NA_real_, n_years)   
  S <- array(NA_real_, dim = c(n_patches, n_years))  
  extinct_year <- NA_integer_        
  
  # Initial conditions
  N[, 1, 1] <- initial_pop_ratio * K
  
  infected_patches_init <- sample(1:n_patches, initial_inf_ratio * n_patches)
  I[infected_patches_init, 1, 1] <- 1
  
  # Derived parameters
  P_f <- 1 / R0
  z <- final_size(R0)
  
  for (k in 1:n_years) {
    
    # Stage 1 -> 2: Growth
    N_begin <- N[, k, 1]
    N_after_growth <- N_begin + r * N_begin * (1 - N_begin / K)
    N[, k, 2] <- N_after_growth
    I[, k, 2] <- I[, k, 1]
    
    # Stage 2 -> 3: Colonization + infection introduction + fizzle
    total_pop <- sum(N_after_growth)
    N_after_col <- (1 - c0) * N_after_growth + c0 * total_pop / n_patches
    N[, k, 3] <- N_after_col
    
    # Compute infection establishment probability (after fizzle)
    if (k > 1) {
      # 1. Total propagules generated by last year's wave in each patch
      nu_S <- nu * S[, k-1]
      
      # 2. Maximum carrying capacity of migrating hosts this year
      rho_cN <- rho * c0 * N_after_growth
      
      # 3. Calculate expected exported and retained propagules (Vectorized)
      lambda_E <- pmin(nu_S, rho_cN) 
      lambda_R <- nu_S - lambda_E
      
      # 4. Total expected propagules present in each patch after colonization
      Lambda_i <- lambda_R + sum(lambda_E) / n_patches
      
      # 5. Infection establishment (Poisson thinning accounts for fizzle)
      lambda_thinned <- alpha * Lambda_i * max(0, 1 - P_f)
      a <- rpois(n_patches, lambda_thinned)
      I[, k, 3] <- as.numeric(a > 0)
    } else {
      I[, k, 3] <- I[, k, 2]
    }
    
    
    # Stage 3 -> 4: Major epidemic
    infected_patches <- I[, k, 3]
    S[, k] <- z * D * N_after_col * infected_patches
    N_after_burnout <- N_after_col - S[, k]
    N[, k, 4] <- N_after_burnout
    I[, k, 4] <- 0
    
    total_inf[k] <- sum(S[, k])
    
    # Early stop if extinct
    if (early_stop && sum(infected_patches) == 0) {
      extinct_year <- k
      
      if (k < n_years) {
        N[, (k+1):n_years, ] <- NA_real_
        I[, (k+1):n_years, ] <- NA_real_
        S[, (k+1):n_years] <- NA_real_
        total_inf[(k+1):n_years] <- NA_real_
      }
      break
    }
    
    # Next year init (stage 4 of year k becomes stage 1 of year k+1)
    if (k < n_years) {
      N[, k+1, 1] <- N_after_burnout
      I[, k+1, 1] <- 0
    }
  }
  
  return(list(N = N, I = I, S = S, total_inf = total_inf, extinct_year = extinct_year))
}

## default parameters 
params0 <- list(
  n_patches = 100,
  n_years = 500,
  K = 1e6,
  r = 0.5,
  c0 = 0.2,
  nu = 5,
  rho = 3,
  alpha = 5e-6,
  D = 1,
  R0 = 2,
  initial_inf_ratio = 0.1,
  initial_pop_ratio = 1
)

#' multiple replicate simulations
mult_sim_mp <- function(nsim, params, verbose = FALSE,
                        ncores = getOption("sim.ncores", 4),
                        seed = NULL) {
  require("parallel", quietly = TRUE)
  if (ncores>1) {
    cl <- makeCluster(ncores)
    
    lp <- .libPaths()
    clusterExport(cl, "lp", envir = environment())
    clusterEvalQ(cl, .libPaths(lp))
    
    clusterExport(cl, c("simulate_metapopulation"))
    clusterExport(cl, c("params"), envir = environment())
    
    clusterEvalQ(cl, quote(library(burnout)))
    
    if (!is.null(seed)) clusterSetRNGStream(cl, seed)
    results <- parLapply(cl, 1:nsim,
                         function(i) {
                           if (verbose) cat(".")
                           do.call(simulate_metapopulation, params)
                         })
    stopCluster(cl)
    rm(cl)
  } else {
    results <- replicate(nsim, {
      if (verbose) cat(".")
      do.call(simulate_metapopulation, params)
    }, simplify = FALSE)
  }
  
  total_pops <- sapply(results, function(res) {
    apply(res$N[, , 1], 2, sum, na.rm = TRUE)
  })
  infected_patches <- sapply(results, function(res) {
    apply(res$I[, , 3], 2, sum, na.rm = TRUE) 
  })
  total_inf <- sapply(results, function(res) {
    res$total_inf
  })
  extinct_years <- sapply(results, function(res) {
    ifelse(is.na(res$extinct_year), Inf, res$extinct_year)
  })
  
  list(total_pops = total_pops, 
       infected_patches = infected_patches, 
       total_inf = total_inf)
}

sumfun <- function(x, nsteps = 100) {
  
  nyr <- nrow(x[[1]])  
  nsim <- ncol(x[[1]])
  
  extinct_years <- apply(x$infected_patches, 2, function(col) {
    extinct_idx <- which(col == 0 | is.na(col))
    if (length(extinct_idx) > 0) {
      return(extinct_idx[1])  
    } else {
      return(NA_integer_)  
    }
  })
  
  n_extinct <- sum(!is.na(extinct_years))
  n_persist <- sum(is.na(extinct_years))
  
  extinction_rate <- n_extinct / nsim
  mean_extinct_time <- mean(extinct_years, na.rm = TRUE) 
  
  yr_vec <- seq(max(1, nyr - nsteps + 1), nyr) 
  
  matrix_vars <- c("total_pops", "infected_patches", "total_inf")
  
  qe_means <- sapply(matrix_vars, function(var_name) {
    y <- x[[var_name]]
    y[x$infected_patches == 0 | is.na(x$infected_patches)] <- NA
    
    mean(y[yr_vec, ], na.rm = TRUE)
  })
  
  c(
    mean_extinct_time = mean_extinct_time,
    extinction_rate = extinction_rate,
    n_extinct = n_extinct,
    n_persist = n_persist,
    qe_means
  )
}